#!/usr/bin/env bash
# install web-server(nginix) in a sever

sudo apt-get update
sudo apt-get install -y ngnix
sudo ufw allow 'Nginx HTTP'

# Write a simple "Hello World!" page to the default HTML directory
sudo su
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart