#!/usr/bin/env bash
# install web-server(nginix) in a sever

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

sudo su
echo "Hello World!" > /var/www/html/index.nginx-debian.html

str_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/ permanent;"
sudo sed -i "s/server_name _;/$str_replace/" /etc/nginx/sites-enabled/default

service nginx restart