#!/usr/bin/env bash
# install web-server(nginix) in a sever

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

sudo su
echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/micoliser permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
service nginx restart