#!/bin/bash env
# Install and configure Load-balancer

# Update the system
sudo apt update
sudo apt upgrade -y

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
defaults
        mode http
        timeout client 10s
        timeout connect 5s
        timeout server 10s
        timeout http-request 10s

frontend main
    bind 54.144.249.182:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 226796-web-02 100.25.136.187:80 check
    server 226796-web-01 54.236.50.4:80 check
EOF

# Ensure HAProxy can be managed via init script
sudo systemctl enable haproxy

# Check if HAProxy is running before restarting
if pgrep haproxy > /dev/null; then
    # Verify the configuration
    if sudo haproxy -c -f /etc/haproxy/haproxy.cfg; then
        # Restart HAProxy to apply the changes
        sudo systemctl restart haproxy
#     else
#         echo "Error: HAProxy configuration is invalid. Please check the configuration file."
    fi
# else
#     echo "Error: HAProxy is not running. Please check the installation."
fi